# Site settings
title: Canyon County Jekyll site
email: webmaster@canyonco.org
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ccjekyll.com" # the base hostname & protocol for your site
twitter_username: canyonco
github_username:  canyoncounty

# Build settings
markdown: kramdown
#highlighter: pygments
highlighter: false
encoding: utf-8
#exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile']
timezone: "America/Boise"
future: false

kramdown:
  input: GFM